language: cpp
script: HelloWorld.cpp


#Hello World is simple as there are no special specs for it to run, 
#even the following could have been determined by default
#minimally, you only need line 1.

#install: make get-deps

#compiler:
#  - clang
#  - gcc
